### PR TITLE
Relative positioning of steps

### PR DESCRIPTION
**Pull request by henrikingo**
Congratulations for creating gh://impress/impress.js! To kickstart the activity, I'm submitting this pull request.

I'm aware that there's discussion of creating a plugin architecture for impress.js. Although simple, these changes could be implemented as a "positioning plugin", which would convert the relative positioning values to absolute positions (as in the core code). In fact, I'm also willing to work on creating such a positioning plugin api, but will need guidance on what type of api/plugin semantics we need to adhere to.

***

Adds support for following new attributes for steps:

    data-rel-x
    data-rel-y
    data-rel-z

These can be used to specify position instead of the absolute position arguments `data-x/y/z`.

The value of `data-rel-x/y/z` is added to `data-x/y/z`. If not specified, also the `rel-*` values are inherited from the previous step. This makes it easy to create a boring presentation where each slide shifts for example 1000px down from the previous.

In addition, adds another demo under examples/classic-slides/. In addition to demoing relative positioning, this demo is also intended to be a much simpler (perhaps boring) and beginner friendly introduction than the existing flashy demo by @bartaz.

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Does this have any relationship with https://github.com/impress/impress.js/pull/473, https://github.com/impress/impress.js/pull/425 or https://github.com/impress/impress.js/pull/131?

**Comment by henrikingo** [comment]
Yes. They're all alternative implementations of the same basic need.

There seem to be 2 general approaches:
 1. Add an attribute to the root element saying something like `positioning="relative"` and then use the same `data-x`, `data-y` and `data-z` attributes, just that the numbers have different meaning. (This should be extended with a possibility to define relative/absolute separately for each step.)
2. Add new attributes, like I have done above: `data-rel-x` and so on. #131 is also in this general category, though different.

I suppose both of these have their own merits. I like second approach for being clearer, not overloading same attribute with meanings that could change. For example if you copy some HTML from a presentation with relative positioning, to another with absolute positioning, you'll have a mess with (1), but it would just work with (2).

All of these call for a "Positioning API", which would allow implementing these as well as more elaborate positioning (like automatically distribute steps along an SVG path...). If an API exist, both types of plugins can coexist, although I think this is quite a core feature (even if a plugin!) so we should also show some leadership and suggest one markup style as the "official" choice. (We can change our minds later if users seem to prefer some other plugin.)

**Comment by henrikingo** [comment]
Oh, I should note that the addition of examples/ and in particular impressConsole.js extends the scope of this pull request quite a lot and its quite improper of me to put unrelated changes into same branch. Basically they reflect the fact that I saw this project as unresponsive and therefore have added things to the branch that were useful for me. The pull request for relative steps must in any case be rewritten to use an api, so from that point of view this should be ignored. 

(But I suggest these are not closed, rather we should respond to all that this kind of functionality will be added via API, and people are welcome to propose such an api, and to do so there must be test coverage first.)

**Comment by bartaz** [comment]
Yes, there are couple of issues/PRs about relative positioning.

My preference was different - I didn't want to introduce any new attributes and use existing `data-x` etc with a different notation (similar to what jQuery has for animations). So for relative positioning you would write `data-x="+=100` or `data-rotation="-=45"`. Having `+=` or `-=` in the beginning of the value would mean that position should be calculated based on previous step.

But I guess discussion which solution is better and which could go into impress.js is something we can have later. For sure this is one of the most requested features.

**Comment by FagnerMartinsBrack** [comment]
> But I suggest these are not closed, rather we should respond to all that this kind of functionality will be added via API, and people are welcome to propose such an api, and to do so there must be test coverage first.

I would argue that the related PRs could be closed for triage if there are too many duplicates or with lots of unrelated changes, there is no value in keep open PRs that cannot be landed as is. One important thing though, is not to forget about important features like this one by maintaining an open issue specific to the purpose of solving this kind of problem **with cross-reference to the proposed PRs to consult later**.

For an example take a look in the issue https://github.com/impress/impress.js/issues/516 and the linked PRs.

**Comment by henrikingo** [comment]
@FagnerMartinsBrack: You're right. Closing current PRs and opening single issue for discussion makes more sense.

@bartaz: Yes, that approach definitively has some merits. It avoids any ambiguity (e.g. you could safely copy paste html into another context) but also avoids adding new attributes. Note that in general I would expect some new positioning schemes to definitively add new attributes, such as positioning along an SVG curve.

**Comment by FagnerMartinsBrack** [comment]
I have closed all other PRs due to the lack of feedback from the OP, except for #425. That one seems to be more easy to review and the OP has demonstrated interest in keep it going. Should we close this in favor of #425 instead? Or, if the amount of changes are going to be reduced for this PR, should we keep this one and close the other?

Despite which one we keep, it will only be landed once we have a proper structure for testing anyway. I just want to focus in only one PR instead of keeping duplicates open.

**Comment by henrikingo** [comment]
Also, either of these has to be rewritten as a plugin, not touching core code.

**Comment by FagnerMartinsBrack** [comment]
@henrikingo So what do you suggest, close this and the other one in favor of #478? It might be worth reducing the amount of open stuff so that we can focus in what can be potentially done in the current state of the project. I guess that landing stuff in the core now is not a problem, since we will probably have to change the whole structure in upcoming releases anyway.

**Comment by FagnerMartinsBrack** [comment]
> So what do you suggest, close this and the other one in favor of #478?

@henrikingo I will assume we should close both and follow the issue #478 instead, as you mentioned above:

> @FagnerMartinsBrack: You're right. Closing current PRs and opening single issue for discussion makes more sense.

**Pull request closed without merging**
