### PR TITLE
Upgrade to typographer quotes

### PR DESCRIPTION
**Pull request by dvdrtrgn**
Looks even classier with "curly" quotes, doncha think?

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
This seems reasonable. Ping @impress/mergers.

**Comment by henrikingo** [comment]
Heh. +1 Since no code is changed.

**Comment by FagnerMartinsBrack** [comment]
I would argue that for the sake of consistency it should be changed for all apostrophes, but then it will be hard to maintain and will make no difference since this PR refers to the ones that are shown in the demo.

**Comment by Pierstoval** [comment]
No problem for me as it's in the demo, so it's ok

**Pull request merged**
