### PR TITLE
Adds an improved mouse wheel event listener

### PR DESCRIPTION
**Pull request by michaelneu**
Including the `impress-scoll.js` allows you to use a wireless mouse with or without a flawless mouse wheel sensor instead of a presenter.

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @minedev , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older PRs like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by minedev** [comment]
Hi, to be honest I haven't tracked this request in a while as there was basically no progress on the other PRs as well. 

I just checked the current demo of impress.js and noticed that this feature is not implemented yet, but could actually come in handy, so I'll track it again. Maybe I'll rewrite it soon, as I now think some parts are quite hacky.

**Comment by FagnerMartinsBrack** [comment]
@minedev Thanks for the feedback! If you want to make sure the problem does not happen then I suggest not relying in the demo, but checking out master and test locally. Although, I still think this feature was not implemented.

Anyway, since you are still tracking we will come back to review this later then, Thanks!

**Comment by FagnerMartinsBrack** [comment]
This is a possible duplicate of https://github.com/impress/impress.js/pull/51. @michaelneu can you please check if the problems discussed there still applies for this PR? Thanks!

**Comment by FagnerMartinsBrack** [comment]
By the way, this PR was opened against `dev`. The new [contributing guidelines](https://github.com/impress/impress.js/blob/8159876c980d409a85f538ea27d524a5f899328a/CONTRIBUTING.md) states that it should be opened against `master`, can you fix that too?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP. If you want to work in the PR again, feel free to comment here to open up the discussion again.

**Pull request closed without merging**
