### PR TITLE
Create Love

### PR DESCRIPTION
**Pull request by Yvonne9996**

### CODE REVIEW

**Comment by dcarral** [comment]
hahahahahahahahahahaha, and this?

**Comment by bartaz** [comment]
all you need is love ;)

**Comment by dcarral** [comment]
Of course! haha. I've just checked out @Yvonne9996's profile expecting at least a "Love" repository. Not lucky enough though ;)

Just for the sake of curiosity, are this kind of contributions somewhat usual in Github?

**Comment by FagnerMartinsBrack** [comment]
Only if you start bikeshedding on it ;)

**Comment by dcarral** [comment]
Got it.

**Pull request closed without merging**
