### PR TITLE
Added powerpoint 'b' functionality to insta-hide the screen

### PR DESCRIPTION
**Pull request by Strikeskids**
Hiding is automatically removed by switching to a new slide. This allows the presenter to go on tangents, returning focus to them instead of the irrelevant slides

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @Strikeskids, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older PRs like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by Strikeskids** [comment]
I'm not emotionally attached to this change, but it would be nice to have this functionality in impress.

**Comment by FagnerMartinsBrack** [comment]
But are you willing to change in the PR, like rebasing into master and solve conflicts, if the need arises?

**Comment by Strikeskids** [comment]
Sure. I can do that.

**Comment by FagnerMartinsBrack** [comment]
Thanks, we will revisit this PR later and will let you know :+1:

**Comment by FagnerMartinsBrack** [comment]
@Strikeskids Can you please provide a visual example of how this feature works and why it should be included in impress.js with 1 or 2 steps for simplicity?

For a visual example, I recommend using LICECap to record the screen in a gif format and upload as a comment here (external links can break after some time).

For the "why" part I recommend stating a real use case in which this feature is useful in a way that it cannot be done outside impress.js.

**Comment by Strikeskids** [comment]
This is useful for when you are giving a talk and would like to directly engage with your audience. By clearing the screen, you remove the visuals as a distraction and get the audience to focus directly on you.

powerpoint b functionality

**Comment by Strikeskids** [comment]
Rebased onto master to merge cleanly.

**Comment by FagnerMartinsBrack** [comment]
> Rebased onto master to merge cleanly.

Thank you, but we will probably only land this once a proper test structure is setup, because this feature will require a regression testing :). We will let you know.

**Comment by henrikingo** [comment]
Hi @Strikeskids 

In my repo, I've now [added your code as its own plugin](https://github.com/henrikingo/impress.js/tree/myfork/src/plugins/blackout). Please have a look.

I made 1 small addition: if you press b again, it will unhide the content. Unfortunately this only works with Chrome. Firefox will for some reason not re-render the empty screen until there's a transition to next slide (which is how your original code works, and is also still there).

Thanks for a cool contribution!

**Comment by henrikingo** [comment]
This is now merged to master. See `blackout` plugin.

**Pull request closed without merging**
