### PR TITLE
Remove excess whitespace

### PR DESCRIPTION
**Pull request by PunkChameleon**
Hey guys!

I know this is completely superfluous, but I'd thought I'd throw it over anyway. I have whitespace turn red in VIM so this was more of a thing for me. Hopefully you find this helpful in some (extremely) small way!

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
The project's author probably used Eclipse to create those files, Eclipse adds by default white space on new lines while other editors don't.

**Comment by FagnerMartinsBrack** [comment]
Hi @PunkChameleon , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older PRs like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

By the way, this seems duplicate of #396.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP. If you want to work in the PR again, feel free to comment here to open up the discussion again.

**Comment by PunkChameleon** [comment]
@FagnerMartinsBrack -- This PR is just for clean-up. There seems to be a lot of extra whitespace through the project, however this is super minimal in priority, but thought it'd still seem valid.

**Comment by FagnerMartinsBrack** [comment]
@PunkChameleon Thanks for the response. Can you please update the commit so that you current account appears as the author?

**Comment by FagnerMartinsBrack** [comment]
We will decide if this should be landed this once #529 is dealt with.

**Comment by FagnerMartinsBrack** [comment]
@PunkChameleon Given the results of #529 it seems we are ready to land this. As asked earlier, can you please update the commit so that your current Github account appears as the author of the commit?

**Comment by PunkChameleon** [comment]
Absolutely, will update tomorrow. Sorry for delay!

**Comment by FagnerMartinsBrack** [comment]
@PunkChameleon Commit author not updated.

**Comment by henrikingo** [comment]
Obsolete after major refactoring. (Note that JavaScript coding style is now enforced with jscs. For other file types, fixing trailing whitespace is still welcome.)

**Pull request closed without merging**
