### PR TITLE
Making impress.js compatible with SVG

### PR DESCRIPTION
**Pull request by csicar**
Why?
Creating the "Presentation-Map" in a vector program is easier than in HTML the data-\* tags can be added there, too.
What was the problem?
SVG-Elements have no Attribute classList, what produces errors. The code adds those Attributes to the SVG-Elements. (I want to add some other things, which makes it even better to use with SVG)

/_Problems with the code-style? -> Tell me a better method of doing it_/

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @csicar, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by csicar** [comment]
Well I am still interested in the project and think that the mesioned SVG
support would make use impress.js easier

Fagner Brack <notifications@github.com> schrieb am Mi., 3. Feb. 2016 13:39:

**Comment by FagnerMartinsBrack** [comment]
Thanks for the feedback!

**Comment by henrikingo** [comment]
Hi @csicar 

Could you share a link or two to an example presentation you did in SVG? I'd like to work on integrating your suggestion, but without example content, it's hard to form an opinion on the code, where to put it, etc.

**Comment by regebro** [comment]
Btw, [Hovercraft](https://github.com/regebro/hovercraft) has svg support, and handles that by translating the SVG path to positions and rotations and uses that to generate the impress.js presentation. That might be interesting as an alternative/temporary solution.

**Comment by henrikingo** [comment]
@csicar I'm trying to re-read this thread to understand...

Is the problem here that you would want to add `class="step"` directly to an svg object? Why can't you have a div first, then the svg object inside it?

**Comment by csicar** [comment]
The reason for having `class=step` inside svg is, that it would allow you to create the svg file in an external tool, like inkscape. Inkscape allows you to modify the svg-xml with a build-in editor

**Comment by henrikingo** [comment]
Ah, that sounds interesting indeed. I think I should look into that myself one day!

FWIW, the patch you've proposed here could now easily be implemented as a plugin. It could be simply called `src/plugins/svg`.

**Comment by henrikingo** [comment]
Hi @csicar 

Could you share an example of where you use impress.js over an svg presentation? (presumably together with the above code.) I think your proposal to support svg makes sense, but I'd want to see it working myself in order to commit this code (as a plugin)

**Comment by henrikingo** [comment]
Closing due to lack of response. This still sounds interesting, so you're welcome to open a fresh PR should you want to work on this again.

**Pull request closed without merging**
