### PR TITLE
Create encrypted environment variables from SauceLabs

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
Related to https://github.com/impress/impress.js/pull/579.

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
@jdalton Can you start a Github review on this?

**Comment by jdalton** [comment]
Let's merge and see if it works :D

**Comment by jdalton** [comment]
@FagnerMartinsBrack

It looks like the `sauce-encrypted-env-vars` file was being treated as text instead of binary.
I added a `.gitattributes` file https://github.com/impress/impress.js/commit/da4c08aa2311f8d2e057d98d7f8fd515e48218c4 to try to enforce binary. Could you please recommit the `sauce-encrypted-env-vars` file again once you've pull down a fresh master.

You can test it by trying to decrypt it locally:
```shell
openssl aes-256-cbc -d -in sauce-encrypted-env-vars -out foo.txt -k $SAUCE_DECRYPT_KEY
bad decrypt
74692:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64/src/crypto/evp/evp_enc.c:330:
```

Before running the command be sure to
```shell
export SAUCE_DECRYPT_KEY=<value_in_https://circleci.com/gh/impress/impress.js/edit#env-vars>
```

**Comment by FagnerMartinsBrack** [comment]
Not sure what is the issue, I have decrypted successfully in my local environment. See #584.

**Pull request merged**
