### PR TITLE
Proposal of documenting a high-level Roadmap

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
I have created [a Roadmap in the wiki](https://github.com/impress/impress.js/wiki/Roadmap) based on what we have discussed so far since 2013 and I would like to propose documenting that so that the strategy is clear for future contributors.

Is the Roadmap correct? Should we document this?

Looking for feedback.

Ping @impress/mergers

### CODE REVIEW

**Comment by carywreams** [comment]
#### periodic ( annual ? ) pros/cons review for typescript re-write
(not meant to be an incendiary request)

**Comment by FagnerMartinsBrack** [comment]
@carywreams Thanks for the suggestions.

This project don't have enough resources to promise periodic releases. Releases happen as they go when we believe there are enough changes to justify a bump (either patch, minor or major) according to the rules of [Semantic Versioning 2.0.0](http://semver.org/)

About typescript, there's no plan in adding transpiler to impress.js. In a few years, TypeScript will become obsolete too as everything else so we don't want to tie ourselves to any dependency that we can't unplug. @bartaz [has made it clear in the past](https://github.com/impress/impress.js/issues/435#issuecomment-178468261):

> I know it can be tempting to put a load of tools into the project (build, transpilers, and what not), but I would love to keep impress.js as simple as possible, the 'old school' way: "here is a JS file, add it to HTML, init impress.js and it works"; I know that at least testing may require some dev tooling, but let's keep it to bare minimum

**Comment by FagnerMartinsBrack** [comment]
bump

**Comment by henrikingo** [comment]
This patch no longer merges cleanly, closing. 

I also updated the wiki page to say that the roadmap was largely achieved!

**Pull request closed without merging**
