### PR TITLE
Template for issues/PRs

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
Everything was grouped in the `/.github` folder to prevent cluttering the root of the project.

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
For inspiration, jQuery have added templates for their PRs/issues: https://github.com/jquery/jquery/pull/3070

**Comment by bartaz** [comment]
Is this `.github` folder a common pattern supported by GitHub? I haven't seen it before.

**Comment by FagnerMartinsBrack** [comment]
@bartaz 

> Is this .github folder a common pattern supported by GitHub? I haven't seen it before.

They have added support for a `/.github` folder in the root to prevent cluttering with a lot of files. See [here](https://help.github.com/articles/creating-an-issue-template-for-your-repository/):

> Decide whether to store your issue template in the repository's root or in a hidden directory called .github ...

Github have been adding great stuff for open source recently, mostly due to [community feedback](https://github.com/dear-github/dear-github).

**Comment by FagnerMartinsBrack** [comment]
Let's land this and see if there will be the need for additional information.

**Pull request closed without merging**
