### PR TITLE
Add option to disable slides 

### PR DESCRIPTION
**Pull request by mhils**
See #428 - needed to clean that up anyway, here's the PR.

``` html
<div class="step" data-y="100">
    I'm step 1!
</div>
<div class="step disabled" data-y="200">
    I am fully visible, but not selected when navigating via arrow keys!
</div>
<div class="step" data-y="300">
    I'm step 2!
</div>
```

Cheers,
Max

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @mhils , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older PRs like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by nathanael-fijalkow** [comment]
Hi,

I'm backing @mhils PR. I think this would be a useful feature, most probably easy to implement.

Cheers,
Nath

**Comment by FagnerMartinsBrack** [comment]
Hi @nathanael-fijalkow, the intent here is to see if the OP is interested in updating the PR, if not then we will track this issue elsewhere. Backing up the PR would not make much difference because you would not be able to update it in @mhils fork due to the default security configurations of Github.

Feel free to create a new PR and keep track of it if we don't receive a response on this one for a few more days.

**Comment by mhils** [comment]
I still think this is a very useful addition, but I'm super busy with other stuff at the moment. @FagnerMartinsBrack, what would you like me to update?

**Comment by FagnerMartinsBrack** [comment]
@mhils Thanks for the response.

I was just asking if you are still following this issue because the next step will be reviewing all PRs one by one, for the moment we are just triaging and closing the ones that are inactive. See https://github.com/impress/impress.js/issues/512.

So, are you still keeping tracking of this PR and willing to make review changes or create tests if necessary later? If so, then we will keep this open.

**Comment by mhils** [comment]
@FagnerMartinsBrack, yes, please.

**Comment by henrikingo** [comment]
Hi @mhils 

As you may or may not know, I've been working on [a plugin API for impress.js](https://github.com/henrikingo/impress.js/blob/myfork/src/plugins/README.md). I've today added a [skip plugin](https://github.com/henrikingo/impress.js/blob/myfork/src/plugins/skip/README.md). If you add `class="skip"` to a step, it will be skipped when steps are navigated with `next()` and `prev()`, but you can still go to the slide with `goto()`, including via clicking a link or typing the hash anchor into the url.

If you could have a look and confirm that this is the same that you had in mind, I would appreciate it!

**Comment by henrikingo** [comment]
skip plugin is now merged to master

**Pull request closed without merging**
