### PR TITLE
Feature: Substeps

### PR DESCRIPTION
**Pull request by patricebeutler**
We needed the "substep"-feature mentioned in the
https://github.com/bartaz/impress.js/issues/81 issue.

We implemented 4 API functions for assigning functions to the steps.
Every mentioned API function takes two parameters: The id of the step
and a function that should be executed on a given time.

There can be one function per step for entering.
There can be one function per step for leaving.
There can be many functions per step that act as "substeps". The user
can then modify everything he wants with simple js. These functions are
called trough next(). The first defined function is executed first.
There can be one function per step that allows resetting the changes
done by the "substep-functions".

Our changes are all backwards-compatible, so it will not break anything
from anyone. We have tested it with a variety of browsers.

We did this with 13 line html (demo), 10 line css (demo) and 46 lines js
(framework). In total less than 70 lines of code added.

If you have something you want to speak about or you are not happy with,
feel free to discuss.

### CODE REVIEW

**Comment by bartaz** [comment]
Hi @patricebeutler, thanks for the commit. I'll have a closer look later.

But can you shortly explain to me how different it is from current `step:enter` and `step:leave` events?
They are also a functions that you can bind to steps. I'm pretty sure currently it is not possible to implement substeps using these events, but maybe with some small changes in how these events work it would be possible?

I'm thinking that maybe if there is a possibility to 'cancel' leaving the step inside of the `step:leave` handler and show a substep instead it would work?

What do you think? Would it be possible to turn your solution into using built in events?

**Comment by patricebeutler** [comment]
Thanks for your quick response.

At first we implemented the two functions for directly handling substeps (addActionToStep and addResetActionToStep). This functions are not events at all and only are used for the handling of the substeps.

At this point everything worked fine. As you noticed, there are also the two functions "addEnterActionToStep" and "addLeftActionToStep". These functions were implemented for usability-concerns and integrity. It is correct that these are like a wrapper for the impress:stepenter and the impress:step:leave events (with the difference they take the id of the step for binding them directly to a step).

With these function you can, as a user, write (pseudocode)

    addEnterActionToStep("someStepId", function(){
        // Some code here
    });

instead of

    addEventListener("impress:stepenter", function(){
        if (step.id == "someStepId"){
            // Some code here
        }
    });

Or in different words: We thought it would be cool for the user to have this possibility. But still, if the user wants to execute code when each and every step is entered, the "impress:stepenter"-event still would be needed.

If you think the "addEnterActionToStep" and the "addLeftActionToStep" are not required for the user, it is easy for us to remove them from the api. The substeps-feature would still work, but the user would have to use the "old" way to bind "stepenter" and "stepleave". This is not awful, but it will result in more lines of coding for the user, since these events are used more as soon as you have substeps. Also, we dont know if every user of impress is able to subscribe to an event and then use an if-statement to determine if the event was fired on a specific slide or not (you know your userbase better than us).

Let me know what you think, thanks again. We are happy to do changes as you like and then file a pull-request again.

**Comment by bartaz** [comment]
You could attach the event to a given step directly to avoid checking the id inside:

```
document.getElementById('someStepId').addEventListener("impress:stepenter", function(){
    // ...
});
````

This may mean that `addEnterActionToStep` and `addLeftActionToStep` are quite obsolete as they do the same thing as events.

But of course it doesn't solve the substeps part.

**Comment by patricebeutler** [comment]
Oh I see now how this works. Our fault. Perfect, the removal of these functions will make the code even smaller. We will remove it in a few hours and then file a new pull-request if that works for you. Then you can do the review and decide if its matching your visions of impress.

**Comment by bartaz** [comment]
Sure. I think if you the fix in same branch it will automatically appear in this pull request, so new one shouldn't be needed.

**Comment by patricebeutler** [comment]
Very good. This is my first time doing this in github, so I didn't know. Thanks for the information. Let me know what you think about the code. Thank you very much.

**Comment by FagnerMartinsBrack** [comment]
Hi @patricebeutler , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older PRs like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by patricebeutler** [comment]
First of all, we are very excited to hear that there is new fire in this project!

I can't answer with a simply yes or no: Yes, we are still tracking this. We strongly think that substeps are one of the most useful features and we still heavily use the pull-requested version today. Still, we aren't sure this is the best way of doing it: At the time of implementing it, our time was very limited, which resulted, from our view, in the smallest possible result: Substeps can be programmed in javascript (this gave maximum flexibility while keeping things simple). There is just one drawback: Everything besides the substeps can be used declaratively.

We submitted the pull-request because the project was very inactive at that time and we thought that this may help some folks. But since there is activity in this project again, I think you should first discuss the best way of achieving it (if you decide to implement substeps). If you conclude that substeps should be created programmatically (and not declaratively), this pull-request does just that (and it's already in use by a few people). So maybe you will be able to use the (or parts of the) code, If you want declarative substeps or something more fancy, I suggest you close the request.

Thank you for your work!

**Comment by FagnerMartinsBrack** [comment]
@patricebeutler Thanks for the feedback!

This PR seems to have been opened against the `dev` branch and it contains a lot of unrelated commits. We will probably revisit this if we need ideas on how to implement substeps.

Thanks!

**Pull request closed without merging**
