### PR TITLE
Support Chinese in impressConsole

### PR DESCRIPTION
**Pull request by kdxcxs**

### CODE REVIEW

**Comment by henrikingo** [comment]
Why not all three?

    case zh:
    case zh-cn:
    case zh-CN:
        ...

**Comment by kdxcxs** [comment]
Cause it's just simplified Chinese,considering the existence of traditional Chinese,I think it's better like that.

**Comment by henrikingo** [comment]
Thanks. This is a cool addition of a major language!

**Comment by kdxcxs** [comment]
My pleasure

**Pull request merged**
