### PR TITLE
Added mouse wheel support.

### PR DESCRIPTION
**Pull request by mtancoigne**
Hi ! I added a mouse wheel support for Impress.js (as proposed in #167)

It's a bit sensitive, but you can have a demo here : http://codepen.io/mtancoigne/full/eZjGxm/

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
@mtancoigne Have you seen the following discussion: https://github.com/impress/impress.js/pull/51#issuecomment-3494748?

When I access you demo using Mac touchpad it has an awful UX, it jumps from the first slide to the third when it should jump from the first to the second. In the gif below you see what happens when I am using the touchpad using the left/right functionality (It might take a while to load, almost 6MB):

example impress

**Comment by mtancoigne** [comment]
@FagnerMartinsBrack Crap... I only tested with my mouse. I'll take a look with a touchpad and try to do something better...

Thanks for your feedback...

**Comment by mtancoigne** [comment]
Oh, and that don't work with firefox :/

I'll come back later with this one :)

**Comment by FagnerMartinsBrack** [comment]
@mtancoigne Feel free to do it. But keep in mind that, since it is not trivial, we might only be able to land this once we have proper regression tests, at least for the algorithm.

Also, we are not even sure if this should be implemented in impress.js core itself or as a pluggable component. If it turns out to be really too hard to implement, we might as well wait until we have a proper API to make it possible attaching this easily in the consumer side.

(In the last case, solutions that show how this could be achieved without changing the core are welcome. We can document that somewhere.)

**Comment by mtancoigne** [comment]
Ok, my mistake was to use a deprecated event, so now it works for firefox too. The only thing that bothers me is the number of mouse steps to use before changing of slide. 

3 was really too short, I tried with 20 wich was good on a touchpad, but on another computer this was too much, forcing me to make avbout two complete wheel scrolls...

Implementing this as a plugin should be good, as long as we can access the current slide from the API, and the numbers of slides.

**Comment by FagnerMartinsBrack** [comment]
> Implementing this as a plugin should be good, as long as we can access the current slide from the API, and the numbers of slides.

Do you want to create an issue or link and existing one about that? It might be worth revisiting.

**Pull request closed without merging**
