### PR TITLE
Corrected the version in the header

### LINKED ISSUE #590: The version in the header is still 0.5.3
While the released version is 0.6.0. Master should probably have 0.6.1-dev or similar as a version in the header.

### PR DESCRIPTION
**Pull request by ChalkPE**
Fixed #590: 0.5.3 -> 0.6.0

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
We need to add the step to the manual release step on the CONTRIBUTING file so that when we release we don't forget to change it manually.

**Comment by FagnerMartinsBrack** [comment]
@jdalton any idea why [the build is failing](https://circleci.com/gh/impress/impress.js/61) for this PR? I tried to rerun and didn't work. I created a [new branch](https://github.com/impress/impress.js/commits/pr-591) on top of this PR and fast forwarded [one commit](https://github.com/impress/impress.js/commit/24d1a4c4c7609433ef48b1047963951fce5592aa) and the [build passed](https://circleci.com/gh/impress/impress.js/60)!

Maybe there are some security restrictions?

@ChalkPE can you please cherry-pick [these changes](https://github.com/impress/impress.js/commit/24d1a4c4c7609433ef48b1047963951fce5592aa) to your PR? Thanks.

**Comment by jdalton** [comment]
@FagnerMartinsBrack Ya it could be. Maybe we should add a check to the script to see if there is a PR environment variable set.

**Comment by FagnerMartinsBrack** [comment]
Fixed on https://github.com/impress/impress.js/pull/593. @ChalkPE Can you please rebase from`master`? Thanks!

**Comment by ChalkPE** [comment]
@FagnerMartinsBrack :white_check_mark:

**Comment by FagnerMartinsBrack** [comment]
@ChalkPE can you please cherry-pick [these changes](https://github.com/impress/impress.js/commit/24d1a4c4c7609433ef48b1047963951fce5592aa) to your PR? Thanks.

**Comment by ChalkPE** [comment]
@FagnerMartinsBrack I'm not sure it's what you wanted, well, cherry-picked 24d1a4c to my branch 😃

**Comment by FagnerMartinsBrack** [comment]
> @FagnerMartinsBrack I'm not sure it's what you wanted

As I mentioned earlier:

> We need to add the step to the manual release step on the CONTRIBUTING file so that when we release we don't forget to change it manually.

[The commit I linked before](https://github.com/impress/impress.js/commit/24d1a4c4c7609433ef48b1047963951fce5592aa) does just that :)

**Comment by ChalkPE** [comment]
:+1:

**Pull request merged**
