### PR TITLE
patch for bugs cannot type space in text box and another typing element

### PR DESCRIPTION
**Pull request by fake-or-dead**
i have found this bug, so i patch it

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @fake-or-dead, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

If you are still tracking this, could you please make it clear what is the problem that this PR fixes with a reproducible example? Thank you.

**Comment by fake-or-dead** [comment]
@FagnerMartinsBrack I'm ok with it since I can fix my problems and seem right impress.js already done fixing this issues ;)

**Comment by FagnerMartinsBrack** [comment]
@fake-or-dead I don't understand very well. Do you mean that impress.js does not have this issue anymore? Could you please rebase this into master and see if this is still a problem?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP. If you want to work in the PR again, feel free to comment here to open up the discussion again.

By the way, this seems a duplicate of #105.

**Pull request closed without merging**
