### PR TITLE
Add encrypted sauce credentials with new key

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Somehow the use of the `-out ~/.circlerc -k $SAUCE_DECRYPT_KEY` command over `-k $SAUCE_DECRYPT_KEY >> ~/.circlerc` causes CircleCI to fail with the message:

```bash
$ npm install
bash: line 1: npm: command not found
npm install returned exit code 127
Action failed: npm install
```

See https://circleci.com/gh/impress/impress.js/45.

@jdalton Any idea why this might be happening? Perhaps let's use the branch on this PR to test it until it works so that we don't clutter `master` with test commits. I have emailed all the data to the e-mail address in your commits.

**Comment by jdalton** [comment]
@FagnerMartinsBrack 
>  Any idea why this might be happening

That's a neat error. I'm not sure what's up with it. It doesn't error the other way so that's nice!
On the fixed commit it looks like the env variables aren't being detected though. More digging!

**Comment by FagnerMartinsBrack** [comment]
@nkbt Since you [helped setting up CircleCI](https://github.com/impress/impress.js/commit/8e97d25a072cd489676e7449abfb073d06ded1cb#diff-29944324a3cbf9f4bd0162dfe3975d88) you can have more experience with it. Any idea why that npm error happens?

**Comment by jdalton** [comment]
Got it working @FagnerMartinsBrack!

Now [sauce is reporting](https://circleci.com/gh/impress/impress.js/52?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) test fails in IE11, Safari 9.1.2, and Safari 8.0.8.

**Comment by jdalton** [comment]
I can confirm the test fails are legit. *(Tested on the real browsers)*

**Comment by FagnerMartinsBrack** [comment]
I guess we need to use this PR to also fix the tests to merge green to master. Make sense?

- [ ] Fix failing tests on IE11, Safari 9.1.2, and Safari 8.0.8.

**Comment by jdalton** [comment]
Fixed the test fails!

**Comment by FagnerMartinsBrack** [comment]
👏 Dude, you're awesome :D

**Comment by kh93918** [comment]
30000$$

**Pull request merged**
