### PR TITLE
"past" and "future" CSS classes can be broken after using goto("#some-id")

### PR DESCRIPTION
**Pull request by frantzmiccoli**
Using goto can break the CSS classes "past" and "future". Here is some code to reproduce the problem on the current demo of impress.js :

    impress().init();
    impress().goto("bored");
    setTimeout(function() {
        impress().goto("ing");
        setTimeout(function() {
            var isPast = document.getElementById("step-2").classList.contains("past");
            console.log(isPast+ " should be true");
    	    var isFuture = document.getElementById("step-2").classList.contains("future");
    	    console.log(isFuture+ " should be false");
        }, 2000);
    }, 2000);

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @frantzmiccoli, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older PRs like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

From what I see according to the comments in this PR, the change is desired, but then we need first to weight the consequences of breaking existing places that are already using impress.js. Maybe we could instead add an issue to track this problem properly and cross-reference this PR to get detailed information later?

**Comment by frantzmiccoli** [comment]
@FagnerMartinsBrack To my opinion this is still worth pulling, though I haven't been in touch with the most recent code base.

**Comment by FagnerMartinsBrack** [comment]
@frantzmiccoli Thanks for the feeedback. We will revisit this PR later then :+1:

**Comment by matheod** [comment]
It took me some time to understand why my presentation bugged. It was because past and future means viewed/neverviewed.

I read again the demo tutorial, and in fact it was write, but maybe make it even more explicit ?

Also, hopping for something like after/before class :)

**Comment by FagnerMartinsBrack** [comment]
I was wondering why this was closed, then realized that this was closed because the `dev` branch was removed and this PR was created against the `dev` branch.

If [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af) still wants to propose this as [stated on this comment](#issuecomment-181382046), feel free to create the PR against master and open up the discussion again.

**Comment by frantzmiccoli** [comment]
@FagnerMartinsBrack Thanks for this point!

**Pull request closed without merging**
