### PR TITLE
Merge examples

### PR DESCRIPTION
**Pull request by henrikingo**
Gentlemen. We've reached the last chapter of the merge saga! (* This PR adds more demo presentations - because there are more features than can be presented in a single demo - and updates the original main demo to use a few of the new features too. Finally some missing updates to DOCUMENTATION.md and lots of updates to README.md.

I also feel like at the end of all this, a new version number is appropriate, and proposing to change to 1.0.0-beta1.

*) After which we can go back and look at the list in #626 . Also, extra addons are still missing, I will post a separate issue to explain.

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
> I also feel like at the end of all this, a new version number is appropriate, and proposing to change to 1.0.0-beta1

We probably need to stay in a beta for some time in order to be able to receive enough feedback.

Any chances we can have the CircleCI failures sorted out before doing that?
https://circleci.com/gh/impress
It could also be because the code is in a different branch. My CircleCI knowledge doesn't go that level.

**Comment by henrikingo** [comment]
> We probably need to stay in a beta for some time in order to be able to receive enough feedback.

That's precisely my plan.

I think the other question is whether we would ask people to test the dev branch, or just merge dev to master and label it beta for a period. My proposal is the latter, since it was always the case that development happens in master. If users want a stable checkout, they should checkout the tagged stable release.

> Any chances we can have the CircleCI failures sorted out before doing that? https://circleci.com/gh/impress
> It could also be because the code is in a different branch. My CircleCI knowledge doesn't go that level.

I'd love to but I can't do anything about it when the saucelabs tests don't run when I post a PR. I've been waiting for you to fix that, afaiu you have the keys and rights? For now, all my PRs were always green.

If you're not able to do that, my plan is to comment out the saucelabs test from CircleCI until this is solved. If it worked, I'd love to fix it, but as long as it doesn't, I would rather spend my own time - for example - writing more tests, rather than figuring out how to run the small amount of existing tests with the more browser versions.

I'm sure the current failure is something simple, simply happening because karma.conf-sauce.js wasn't updated the same way that karma.conf.js. Probably if you looked at a diff of karma.conf.js in master vs dev, that would already reveal what the needed fix is. But as long as I can't test it, I can't of course do anything.

**Comment by FagnerMartinsBrack** [comment]
@henrikingo I'll forward to you an e-mail with the Sauce Keys. I'm not sure if I will have the opportunity to look into it anytime soon.

**Comment by henrikingo** [comment]
Thanks for sharing the keys. As I suspected, it was just a matter of applying the same changes as I did to karma.conf.js.

Good timing too, thanks for being responsive. MongoDB twice per year allows us to spend 3 days hacking on personal projects, which for me was always impress.js. This final merge is happening during those 3 days. (Today being the last one.) Just felt I should credit my employer for letting me do this.

**Comment by FagnerMartinsBrack** [comment]
> Good timing too, thanks for being responsive. MongoDB twice per year allows us to spend 3 days hacking on personal projects, which for me was always impress.js. This final merge is happening during those 3 days. (Today being the last one.) Just felt I should credit my employer for letting me do this.

Luckily you have this opportunity, it's not every company that has such Open Source culture built in. Most companies consume Open Source but don't contribute enough. I guess [everybody knows it](https://www.youtube.com/watch?v=VS6IpvTWwkQ) at this point.

**Comment by FagnerMartinsBrack** [comment]
Somebody also got in touch in regards to Open Collective in the past for impress.js. I have also forwarded that e-mail. Since you're investing more time on this I guess you might find a way to use that to help the project.

**Comment by henrikingo** [comment]
Ah yes. We should absolutely work with them once this merging is over. Github also now allows to label tickets as good first ticket. Several items in #626 will be good for that.

**Comment by FagnerMartinsBrack** [comment]
> Github also now allows to label tickets as good first ticket.

Yeah, [I've started doing that too](https://github.com/js-cookie/js-cookie/issues/226).

**Pull request merged**
