### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by matthiasn**

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @matthiasn it seems that the word is correct, it means that despite HTML and CSS you need to have design skills too.

**Comment by matthiasn** [comment]
Sure, but then it would be "you need to be a designer, too".

**Comment by FagnerMartinsBrack** [comment]
Wang to update the PR? :)

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP. If you want to work in the PR again, feel free to comment here to open up the discussion again

**Pull request closed without merging**
