### PR TITLE
Shift+Tab now goes back to previous step. Issue #446 fixed.

### PR DESCRIPTION
**Pull request by bartvanderwal**
See comments in new issue #446.

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @bartvanderwal, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by bartvanderwal** [comment]
Hi @FagnerMartinsBrack .

Good busy! (that's Dutch, for 'doing good work :P).

To be honest I haven't been tracking this project, and didn't do much with it anymore. This little contribution of mine is but a vague memory. But now I do remember that there were more people who asked for this, and suggested this. And as far as I remember it worked. And now I look back at #446 you also did this in your fork or tested it or something.

Was this change already done? Otherwise I would say just accept the pull request :smile:.

**Comment by FagnerMartinsBrack** [comment]
@bartvanderwal thanks for the response. Until now the master does not have this fix.

For now we are not accepting any Pull Request, just cleaning up old issues. We will leave only the issues in which the OP is still interested in making the required changes if necessary (like rebasing on top of master if the codebase changes), mostly when there is duplicates like this one. That helps us to reduce the noise.

If you are not interested in keep tracking this we can close the PR and check if there is anybody else who opened a duplicate and wants to keep tracking it (or we track ourselves using issues).

What do you think?

**Comment by bartvanderwal** [comment]
I don't understand your focus on if OP keeps track of a bug. Shouldn't you rather decide to accept or not based on relevance of a change, whether it's in line with idea of the package and code quality.

The latter I'll leave to you, but the former is pretty evident given that the author mentioned the shift-tab specifically as something he should have done, but hadn't got around to yet.

**Comment by FagnerMartinsBrack** [comment]
> I don't understand your focus on if OP keeps track of a bug

Its not about keeping track of a bug, but more about keeping track of one opened PR. If the OP doesn't keep track, then it will be harder to get a response from code review or if the PR should be rebased because the master branch changed at some point.

I agree that this change should be landed soon, but before we go into that we are going to close duplicates and try to reduce the amount of opened issues/PR in order to understand better the more important requests we have for the moment. This is definitely one of them.

**Comment by bartvanderwal** [comment]
Ah and after reading this comment of yours;

https://github.com/impress/impress.js/issues/435#issuecomment-62306959

It seems to me that you should just change this (original) repo to yours, since you added the shift-tab since you added a lot of other goodness like unittests and JSHint and AMD!

About the bower stuff, since you mention you don't know about it there, that just requires adding a bower.json (if it 's not there), adding the git repo url in there, and a version (dame version as in package.json) and doing a bower register once. Then after that you need to bump that version number and commit that each time you want a change to be available to Bower users (the Bower system will detect that). For us not-so-hipsters still on Bower, which I think are still
considerable.

And with whom you should be able to identify as you called jQuery the most succesfull JS package, which is true, but no real hipster would say :P.

You can then indeed close this issue. And I know think I understand your context better.

**Comment by FagnerMartinsBrack** [comment]
Thanks for the response.

> It seems to me that you should just change this (original) repo to yours, since you added the shift-tab since you added a lot of other goodness like unittests and JSHint and AMD!

Unfortunately I can't just change because it's been some time since I made that fork, but we definitely will import some ideas to the main impress.js repo.

> You can then indeed close this issue. And I know think I understand your context better.

Ok. Again, thanks for the feedback. If you think we need to reopen this PR/issue later, just ping back :+1:

**Comment by Pierstoval** [comment]
I tagged this issue with `future` because this is definitely a feature we'll need in the future :)

**Comment by FagnerMartinsBrack** [comment]
Shouldn't we cross-reference and track the issue using the actual #446 instead? We could cherry-pick this commit later if the codebase doesn't change too much.

**Comment by Pierstoval** [comment]
Yeah you're right, but IMO we still should label one of the two with the tag, it really helps searching for what we'll implement after refactoring the codebase.

**Comment by FagnerMartinsBrack** [comment]
> it really helps searching for what we'll implement after refactoring the codebase.

:+1:

**Pull request closed without merging**
