### PR TITLE
hide cursor in fullscreenafter a configured delay without movement

### PR DESCRIPTION
**Pull request by sclausen**
For making presentations better, it would be great, if the mouse cursor hides after going to fullscreen.
This commit implements this behavior.

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @sclausen, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older PRs like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by Pierstoval** [comment]
This feature should be enabled/disabled by the developer to avoid behavior misunderstanding. Even if I like the feature I'd set it to `off` by default

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP. If you want to work in the PR again, feel free to comment here to open up the discussion again

As this feature seems to be pretty useful I have created a new issue to track it: #527

**Comment by sclausen** [comment]
@FagnerMartinsBrack sorry for the long delay, but I didn't know how to properly respond. Sure I didn't track this issue, because it has been so very very long ignored. So, what should or could be done now?

**Comment by FagnerMartinsBrack** [comment]
Are you willing to rebase/fix code review/etc if asked to do so? If yes, then I will reopen as stated in the last comment.

**Comment by sclausen** [comment]
Sure I'll do.

**Comment by sclausen** [comment]
@FagnerMartinsBrack weren't my changes good to merge?

**Comment by FagnerMartinsBrack** [comment]
@sclausen I'm sorry, I have no idea why this was closed o.O.

**Comment by FagnerMartinsBrack** [comment]
Oh, looking again it seems that this was closed automatically by Github because the `dev` branch was removed (this PR was opened against the `dev` branch). See #521 for context.

Can this be opened against `master`?

**Pull request closed without merging**
