### PR TITLE
add css classes to the body using data-cls

### PR DESCRIPTION
**Pull request by Marvin182**
Hey,

don't know if you want to have this feature in impress.js. I found it very useful in various cases.

Anyway thanks for your awesome work! :)

Marvin

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @Marvin182, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by Marvin182** [comment]
Hi,
I still this this was a missing option, but as I do not longer use impress.js I would not be upset if you decide to discard this idea ;)

**Comment by FagnerMartinsBrack** [comment]
@Marvin182 Thanks for the response!

We can close the PR, but we can keep the idea for later ;D.

That said, do you remember what this feature was about? I don't understand very well the use case for this.

**Comment by Marvin182** [comment]
I wanted to have a way to change the style of the body element in the steps.

**Comment by FagnerMartinsBrack** [comment]
Couldn't you do that with the `stepenter` event? Is this change really necessary?

**Comment by Marvin182** [comment]
I believe not or at least not in a nice, convenient way. But seriously, I told you I do not use impress.js any longer and you already to rejected this 2 year old pull request, why should I waste my time to discuss with you if it would have been necessary or not?

**Comment by bartaz** [comment]
Impress.js currently adds automatic class to body element on each step based on the step id (for example `impress-on-step-5`. This can be used to style body element differently and should be sufficient for most cases.

But of course option to override this automatic class with some custom one can be added too if we find it useful.

**Comment by FagnerMartinsBrack** [comment]
> why should I waste my time to discuss with you if it would have been necessary or not?

Because this discussion can be useful for future developers, just like you thought the code could be useful when you opened the Pull Request 2 years ago.

Anyway, as [per the comment above](#issuecomment-181367766) it seems that now the feature can be accomplished using other existing means.

Thanks for the Pull Request.

**Comment by Marvin182** [comment]
@bartaz The automatic class is sufficient for most use cases, but for some presentations I found it handy to combine and reuse classes and that is what this code can do. I think it is more a design decision, code complexity versus features. Up to you ;)

**Pull request closed without merging**
